package com.autopass.person.model.response;

import java.time.LocalDate;

import com.autopass.person.model.Person;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;

import io.swagger.annotations.ApiModelProperty;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@JsonInclude(Include.NON_EMPTY)
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class PersonResponse {

    @JsonIgnore
    private Person person;

    @ApiModelProperty(value = "Person's autogenerated Id.")
    public String getId() {
        return person.getId();
    }

    @ApiModelProperty(value = "Person's associated document number, following type pattern.")
    public String getDocumentNumber() {
        return person.getDocumentNumber();
    }

    @ApiModelProperty(value = "Person's complete name.")
    public String getFullName() {
        return person.getFullName();
    }

    @ApiModelProperty(value = "Person's social name.")
    public String getSocialName() {
        return person.getSocialName();
    }

    @ApiModelProperty(value = "Person's gender.")
    public String getGender() {
        return person.getGender();
    }

    @ApiModelProperty(value = "Person's birth date.")
    public LocalDate getBirthDate() {
        return person.getBirthDate();
    }


    @ApiModelProperty(value = "Person's associated e-mail address.")
    public String getEmail() {
        return person.getEmail();
    }

}
